### ISSUE TITLE
Backports from Bitcoin

### ISSUE THREAD

**Issue by CharesFang** [litecoin-project/litecoin#763]
We recently investigated the Bitcoin issues which are related to privacy protection, vulnerability patches, or security enhancements. We have also checked the `litecoin` source code. Results show that these issues and their PRs are not backported yet. Henceforth, we suggest that `litecoin` should backport the PRs listed below for the considerations of software security and integrity. 

- [ ] Bitcoin [PR#17906](https://github.com/bitcoin/bitcoin/pull/17906), avoid uninitialized reads.
- [ ] Bitcoin [PR#16572](https://github.com/bitcoin/bitcoin/pull/16572), fix a `Char` variable used as `Bool`.
- [ ] Bitcoin [PR#16251](https://github.com/bitcoin/bitcoin/pull/16251), improve `signrawtransaction` error reporting.
- [ ] Bitcoin [PR#15323](https://github.com/bitcoin/bitcoin/pull/15323), fix race condition in `mempool_persist.py`.
- [ ] Bitcoin [PR#15305](https://github.com/bitcoin/bitcoin/pull/15305), fix crash when disconnecting fail.

Some of these issues and PRs are not severe security-related, but backports can avoid the chaos ecosystem of Bitcoin-forked projects and the potential vulnerabilities in the future. 

Reported by `de957ad9679f28a38f02f00cc7928bce8fb424882ff060a3c09c32895b1474cc`.

**Comment by losh11** [comment]
Closing, recommend not backporting due to imminent release with fixes applied.
